### PR TITLE
3.0

### PR DESCRIPTION
**Pull request by dongilbert**

### CODE REVIEW

**Comment by arabtornado** [comment]
btw there is a bug in using json_encode instead of http_build_query, However it works nicely with Basic Auth with both POST and GET but for Oauth2 only GET works.. so if you tried to create a contact using Oauth you will get this error

`errors: {
0: {
code: "401",
message: "The response has unexpected status code (401)."
}`

**Comment by dennisameling** [comment]
Last blocker for this PR is https://github.com/mautic/mautic/issues/9224, then we should be good to merge. Currently trying to work on a fix for this.

**Comment by dennisameling** [comment]
Just fixed the last bits to get CI to pass:
- Added reference to the new `email_stat_replies` endpoint as per https://github.com/mautic/mautic/pull/7718. 
- Fixed CS
- Checkout Mautic from the `staging` branch so that the API library always tests against the latest available code

If CI indeed passes, we're good to merge this PR 🚀

**Comment by dennisameling** [comment]
We're good to merge now - thanks @dongilbert and everyone else involved for making this happen! 😄

**Pull request merged**
