### PR TITLE
Add OAuth1a spec support to tests

### PR DESCRIPTION
**Pull request by alanhartless**
This adds support for using the OAuth1a spec for tests. Refer to the local.config.php.dist file for the changes needed.

### CODE REVIEW

**Comment by mbabker** [comment]
Works OK for me.  One suggestion; the bottom config block implies that entire section is only for OAuth1A, maybe make that a bit more clear?

**Comment by escopecz** [comment]
It works for me too (finally). The dev env doesn't seem to remember the accessToken. The authentication works without problem, but calling some endpoint returns 'access_denied: OAuth2 authentication required' error message.

So this does not work  (referring to local.config.php):
```
'apiUrl'          => 'http://example.com/index_dev.php/api/',
```
but this does:
```
'apiUrl'          => 'http://example.com/api/',
```

**Comment by alanhartless** [comment]
@mbabker  technically the bottom config block is only for OAuth1a.  OAuth2 only cares about the access token when making api endpoint calls and thus doesn't need the client id, etc.  OAuth1a requires the other stuff in addition to the token in order to build the authorization header.

@escopecz If prod works but dev does not, then it sounds more like a local cache issue? Did you try clearing your cache for both environments?

**Comment by mbabker** [comment]
Might need to make the apitester page more clear then.  The fields are there so I just assumed it was needed for the API always.

**Comment by alanhartless** [comment]
The API tester has them in order to test the whole auth process which requires user interaction to login, grant/revoke, etc in addition to API endpoints.

The unit tests are (currently) written to only test the endpoints although Symfony unit tests has ways of automating form submissions if we wanted to test the whole oauth processes with the tests as well.

**Comment by escopecz** [comment]
Grrr, it was the cache. Clearing dev cache solves it. So all works fine. I also tested that OAuth2 doesn't need clientKey, clientSecret nor callback to work. :+1:

**Pull request merged**
