### PR TITLE
Add DDEV first-run experience ✨

### PR DESCRIPTION
**Pull request by dennisameling**
How to test:

- Checkout this branch locally
- Run `ddev start`
- The first-run experience should start 🚀 try answering "yes" so that a local Mautic instance is created

### CODE REVIEW

**Review by RCheesley — APPROVED** [review]
That is super cool! Followed the instructions, Mautic was set up by DDEV automagically in /mautic .... total game changer!

🚀  😍  🎉

**Comment by dennisameling** [comment]
Note to self: add some info about this first-run experience to the README

**Comment by dennisameling** [comment]
Closing and re-opening now that https://github.com/mautic/mautic/pull/9667 is merged 🚀 tests should pass now

**Comment by RCheesley** [comment]
Seems that there are still some tests failing @dennisameling :(

**Pull request merged**
