### PR TITLE
psr/log 3.0 compatible, php 8.0

### PR DESCRIPTION
**Pull request by christian-beckmann**
setLogger has correct implementation of LoggerAwareInterface, do to issue https://github.com/mautic/api-library/issues/273

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @christian-beckmann thanks for the PR - can you please sign the Contributors Agreement linked above (you can do this online). Thanks!

**Comment by christian-beckmann** [comment]
Take it or leave it.

**Comment by RCheesley** [comment]
Thanks, we would love to accept the contribution but we can't do that without the contributors agreement being signed. That applies across all Mautic repos for all contributors.

If you prefer not to sign it we will close the PR as it won't be accepted without it.

**Comment by Rocksheep** [comment]
Is there a way how I can help to get this PR approved? I really need this fix for one of my projects.

**Comment by escopecz** [comment]
This needs 2 things to get it merged:
1. Fix the CI checks
2. Two approvals that it works correctly and the code has no issues.

**Comment by escopecz** [comment]
Another issue with this PR that I've missed is that the author do not want to sign CLA, so we cannot merge it into the open source project. So i'll close it and someone else must make the changes.

**Comment by benfavre** [comment]
what a joke lmao

**Comment by PierreAmmeloot** [comment]
@christian-beckmann can you sign the Contributor License Agreement please?

**Pull request closed without merging**
