### PR TITLE
Ensure strlen is not called with NULL values to avoid a deprecation w…

### LINKED ISSUE #280: Deprecated error on isOauth1 function using php8.1
The \Mautic\Auth\OAuth::isOauth1() method is potentially being called before the _request_token_url attribute is initialized. As result, a NULL value is passed to the strlen() php function, causing a deprecation warning.

Deprecated function: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Mautic\Auth\OAuth->isOauth1() (line 525 of /.../vendor/mautic/api-library/lib/Auth/OAuth.php).
Mautic\Auth\OAuth->isOauth1() (Line: 564)
Mautic\Auth\OAuth->prepareRequest('https://mautic.toerismevlaanderen.be/api/forms', Array, Array, 'GET', Array) (Line: 115)
Mautic\Auth\AbstractAuth->makeRequest('https://mautic.toerismevlaanderen.be/api/forms', Array, 'GET', Array) (Line: 259)
Mautic\Api\Api->makeRequest('forms', Array) (Line: 399)
Mautic\Api\Api->getList('', 0, 100, '', 'ASC', 1, 1) (Line: 234)

### PR DESCRIPTION
**Pull request by dlopez-akalam**
Closes #280

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
Thanks! 👍

**Comment by escopecz** [comment]
@dlopez-akalam please sign CLA so this could be merged.

**Comment by dlopez-akalam** [comment]
Hi @escopecz, I singed the agreement yesterday. I wonder it takes a few days to be validated.

**Comment by escopecz** [comment]
[clabot:check]

**Comment by escopecz** [comment]
@cla-bot check

**Comment by escopecz** [comment]
@all-contributors please add @dlopez-akalam for code

**Pull request merged**
