### PR TITLE
Added data to sendToContact and new sendCustomToContact API

### PR DESCRIPTION
**Pull request by kuzmany**
API modification for https://github.com/mautic/mautic/pull/4693

### CODE REVIEW

**Comment by escopecz** [comment]
There are some conflicts

**Comment by kuzmany** [comment]
Fixed

**Comment by luizeof** [comment]
@escopecz  any chance to Merge this ?

**Comment by escopecz** [comment]
I can see one more problem there. The shorthand arrays (`[]`) are used there, but this library [still supports PHP 5.3.7](https://github.com/mautic/api-library#requirements) so those must be replaced with `array()`. I know it sucks! We'll have to release a new major version with the PHP version update.

**Comment by kuzmany** [comment]
@escopecz fixed

**Comment by escopecz** [comment]
Thanks @kuzmany! Now the Mautic PR must be tested, docs added. But could you also add tests to those new API endpoints to https://github.com/mautic/api-library/blob/master/tests/Api/EmailsTest.php ? I really try to get all endpoints covered by those tests because any human can test those manually before every Mautic release. It must be automated.

**Comment by kuzmany** [comment]
@escopecz I'll take a look later. THX

**Comment by escopecz** [comment]
@kuzmany please resolve the conflicts.

**Pull request closed without merging**
