### PR TITLE
Access and authorize token URLs populated in the API library

### PR DESCRIPTION
**Pull request by escopecz**
It makes implementations easier since needed URLs are populated in the library itself.

### CODE REVIEW

**Comment by alanhartless** [comment]
@escopecz with this should change, should we keep BC support by leaving these lines https://github.com/mautic/api-library/pull/9/files#diff-f5f73cd70606a15ada3ed89af540914bL148 and maybe add some kind of if/else statements?

**Comment by mbabker** [comment]
As we haven't tagged a 1.0 yet, I think the B/C breaks are OK if they're justified.

**Comment by alanhartless** [comment]
I'm good with that. Actually, as I'm thinking about it, I don't think it'll be a BC issue at all since it uses reflection to pass in the arguments.

**Comment by alanhartless** [comment]
Sorry, I'm on crack. It would be as it's expecting a new $baseurl and $version now. But I'm still okay with not having BC support as I don't think many, if any, outside of are using this yet?

**Comment by escopecz** [comment]
I implemented this version of API library with Joomla plugin (https://github.com/mautic/mautic-joomla/pull/16) and it works fine. It was not BC though. Different parameters has to be added to the `\Mautic\Auth\ApiAuth::initiate()` function. But it makes new implementations easier.

**Pull request merged**
