### PR TITLE
Remove composer.lock

### PR DESCRIPTION
**Pull request by JaZo**
As discussed in https://github.com/mautic/api-library/pull/272#issuecomment-1508671724

### CODE REVIEW

**Comment by escopecz** [comment]
Thanks! This is good to go but blocked by https://github.com/mautic/api-library/pull/290/files#r1168363521

**Comment by escopecz** [comment]
Could you please rebase? The tests are fixed in the latest main branch

**Comment by JaZo** [comment]
Check, here you go!

**Review by escopecz — APPROVED** [review]
Thank you!

**Pull request merged**
