### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by escopecz**
https://github.com/mautic/api-library/pull/270 updated all dependencies and I cannot install the library on PHP 7.3 anymore:
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for psr/container 1.1.2 -> satisfiable by psr/container[1.1.2].
    - psr/container 1.1.2 requires php >=7.4.0 -> your PHP version (7.3.29) does not satisfy that requirement.
  Problem 2
    - psr/container 1.1.2 requires php >=7.4.0 -> your PHP version (7.3.29) does not satisfy that requirement.
    - symfony/service-contracts v2.5.1 requires psr/container ^1.1 -> satisfiable by psr/container[1.1.2].
    - Installation request for symfony/service-contracts v2.5.1 -> satisfiable by symfony/service-contracts[v2.5.1].
```
So I [reverted that commit](https://github.com/mautic/api-library/commit/6239d4fd5b82aff263fae710d53d98c7da33c743) and [updated just the psr/log dependency](https://github.com/mautic/api-library/commit/248e997004451f53fd6644c347c952e400ceeabd):
```
$ composer update psr/log
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating psr/log (1.1.3 => 1.1.4): Downloading (100%)         
Writing lock file
Generating autoload files
```

### CODE REVIEW

**Comment by escopecz** [comment]
@dennisameling do you have a clue what could be so wrong? Here is how the tests look like when I run it manually on my local:
```
.........................S.......S.............................  63 / 304 ( 20%)
................S.............................................. 126 / 304 ( 41%)
...............F.FFFFF......................................... 189 / 304 ( 62%)
...........SS....S..................................S.......... 252 / 304 ( 82%)
....................................................            304 / 304 (100%)
```
And this is from GitHub Actions:
```
................FFFFFFF.......FSFFFFFF.FFFFFFFFFFF.FFFFFFS..FFF  63 / 304 ( 20%)
FFFFFFF.FFFFFFFFFFFFF............SFFFFFFFF.FFFF.FF.FFFFFF.FFFFF 126 / 304 ( 41%)
FFFFF.FFFFFF.FFFFFFFFFFFFF.FFFFFF.FFFFFFFFF.FFF.FFFFFFF.FFFFFFF 189 / 304 ( 62%)
FFF.FFFFFF.FFFFFFFF.FFFFFFF.EEEEEEEE.FF.FFFFFF.FFFFFF.FFFFFFFFS 252 / 304 ( 82%)
.FFFFFF.FFFFFFF.FFFFFF.SSFFFFS.FFFFFFFFFFEFFFFFFFFF.            304 / 304 (100%)
```
It looks like the configuration to connect to the Mautic instance is wrong.

**Comment by escopecz** [comment]
Hmm, yes, it looks like an Apache config issue rather than application issue:
```
The response has unexpected status code (403).

Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
<hr>
<address>Apache/2.4.53 (Ubuntu) Server at localhost Port 80</address>
</body></html>
```

**Comment by JaZo** [comment]
I'm certainly with you! We never commit the lock file in our packages and I rarely see it done by others.

**Comment by escopecz** [comment]
I'll close this PR as similar was done by other PR it seems. @JaZo would you mind creating a special PR for removing composer.json?

**Comment by JaZo** [comment]
Sure thing!

**Pull request closed without merging**
