### PR TITLE
ensure 5.x and 4.4 can use the same logic

### PR DESCRIPTION
**Pull request by mollux**

### CODE REVIEW

**Review by escopecz — APPROVED** [review]
👍

**Comment by escopecz** [comment]
I've run the M4.4.10 release on this branch and it ended up with several failures:

https://github.com/mautic/api-library/actions/runs/5736933636/job/15547552524

**Comment by RCheesley** [comment]
@mollux are you able to take a look at this so we can make the 4.4.10 release?

**Comment by mollux** [comment]
@escopecz 

I found a solution to run the tests both on M4 and M5:
* M5: https://github.com/mautic/api-library/actions/runs/5923005394
* M4: https://github.com/mautic/api-library/actions/runs/5923007453 (using https://github.com/mautic/mautic/pull/12617 as reference PR)

changes since last time are:
* awareness of the mautic version and some small test data changes
* removal of paratest to prevent a race condition in M4. 
  This results in 30 - 50 seconds more test time, but that's still a huge difference compared to before this PR

The last change should also solve the random test failure on the daily tests, as it's the same race condition

**Review by fedys — APPROVED** [review]
Thanks @mollux! 👍

**Comment by escopecz** [comment]
Amazing work. Thanks Mattias!

**Pull request merged**
