### PR TITLE
Fix OAuth Authorization

### PR DESCRIPTION
**Pull request by Wise-Gorilla**
This edit fix the oAuth issue that raised when changed the POST to use  json_encode instead of http_build_query #216

### CODE REVIEW

**Comment by dennisameling** [comment]
@kuzmany Absolutely. Not sure why Travis is failing; will take a look during the weekend 👍

**Comment by kuzmany** [comment]
@dennisameling We should merge this fix or https://github.com/mautic/api-library/pull/218 to master
A lot of people download master or last package and doesn't work for them.

**Comment by dennisameling** [comment]
@kuzmany This needs a bit of work to fix for M3, there is even a special branch for M3 which hasn't been released yet https://github.com/mautic/api-library/tree/3.0 🤦🏼‍♂️ I was planning to release a new version of the API library on Monday together with the 3.1 release, as some fixes will need to be done to the automated tests first. To be continued; thanks for the heads-up!

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dennisameling** [comment]
Thanks @Wise-Gorilla - merging this for the V3 release of the API library 🚀

**Pull request merged**
