### PR TITLE
Additional Api improvements, basic auth

### PR DESCRIPTION
**Pull request by MarkLL**
These changes rely on PR #70 being in place first.

Includes a fix for the Data class plus an initial test case and replacement of deprecated methods.

**Basic Authentication Support Added**
I've added support for the BasicAuth functionality now in Mautic. See the update to the readme for usage instructions plus I've updated the local.config.php.dist file with instructions. 

To Test this PR:
1. See #70 and follow instructions. Install this PR
2. Run the included test for the data class `phpunit tests/Api/DataTest.php`
3. Run the BasicAuth test case by running `phpunit tests/Api/Auth/BasicAuthTest.php`

### CODE REVIEW

**Comment by alanhartless** [comment]
@MarkLL Unfortunately, we didn't bump the minimum PHP requirement in 2.0 for this so we're stuck at supporting 5.3.7 until 3.0 of the API. I see that there are some PHP 5.4 code uses ([] for example). Can you update the code to PHP 5.3 compatibility? In 3.0, we'll be sure to bump the PHP minimum version. 

Thanks!

**Comment by MarkLL** [comment]
Thanks @alanhartless ; should be fixed now. Found a couple of others that must of slipped through. Might be a good pre-commit learner for me. :)
Cheers

**Comment by alanhartless** [comment]
@MarkLL Thanks! Would you also merge in master to resolve the conflict?

**Comment by MarkLL** [comment]
@alanhartless Sorry, Github newbie. Hopefully I did it correctly :)

**Comment by jozephbrasil** [comment]
That is great! I am waiting for a long time PR #73 to be merged! :-D

**Comment by jozephbrasil** [comment]
Waiting for merge.... tic, tac, tic, tac....

**Comment by escopecz** [comment]
@jozephbrasil help us test the PRs if you want us to merge it fast.

@MarkLL I get a lot of failures during running phpunit. I updated my local.config.php to use the format in local.config.php.dist, but it still fails whatever I do. If I use Oauth2, it fails on:
```
1) Mautic\Tests\Api\Auth\BasicAuthTest::testConfigReady
AuthMethod Check failed. Check AuthMethod in local.config.php.
Failed asserting that false is true.
```
It should skip this test for Oauth2, right? As there is this comment in the .dist config: "If (AuthMethod) commented out, will default OAuth." But it still fails there.

If I configure BasicAuth, I get this error:
```
1) Mautic\Tests\Api\AssetsTest::testGetList
access_denied: OAuth2 authentication required
Failed asserting that true is false.

/var/www/html/mautic-api/tests/Api/MauticApiTestCase.php:44
/var/www/html/mautic-api/tests/Api/MauticApiTestCase.php:94
/var/www/html/mautic-api/tests/Api/AssetsTest.php:27
```

It's probably caused by my bad configuration, but could you help me out run the tests successfully?

**Comment by MarkLL** [comment]
@escopecz the BasicAuth test is doing what it was designed to do. If basic Auth is not configured testConfigReady will fail and the 2 remaining tests are skipped. I'm open to ideas on the best approach to handle this.
 I'll have a quick look at assets tests, but I must admit, I still have not managed to got them all to pass.

**Comment by MarkLL** [comment]
@escopecz as for the Assets test, I found if it's not an admin user it might fail!
```
C:\MarkLL\api-library>phpunit -v --debug --tap tests\Api\AssetsTest.php
TAP version 13
ok 1 - Mautic\Tests\Api\AssetsTest::testGetList
not ok 2 - Failure: Mautic\Tests\Api\AssetsTest::testGetListOfSpecificIds
  ---
  message: 'You do not have access to the requested area/action.'
  severity: fail
  ...
not ok 3 - Failure: Mautic\Tests\Api\AssetsTest::testCreateWithLocalFileGetAndDelete
  ---
  message: 'You do not have access to the requested area/action.'
  severity: fail
  ...
not ok 4 - Failure: Mautic\Tests\Api\AssetsTest::testCreateWithRemoteFileGetAndDelete
  ---
  message: 'You do not have access to the requested area/action.'
  severity: fail
  ...
ok 5 - Mautic\Tests\Api\AssetsTest::testEditPatch
not ok 6 - Failure: Mautic\Tests\Api\AssetsTest::testEditPut
  ---
  message: 'You do not have access to the requested area/action.'
  severity: fail
  ...
1..6
```
however If I use an admin user, the only one failing is the List of IDs because in my mautic test environment that's still broken. (will upgrade and test again)
```
TAP version 13
ok 1 - Mautic\Tests\Api\AssetsTest::testGetList
not ok 2 - Failure: Mautic\Tests\Api\AssetsTest::testGetListOfSpecificIds
  ---
  message: 'Failed asserting that 0 matches expected 3.'
  severity: fail
  data:
      got: 0
      expected: 3
  ...
ok 3 - Mautic\Tests\Api\AssetsTest::testCreateWithLocalFileGetAndDelete
ok 4 - Mautic\Tests\Api\AssetsTest::testCreateWithRemoteFileGetAndDelete
ok 5 - Mautic\Tests\Api\AssetsTest::testEditPatch
ok 6 - Mautic\Tests\Api\AssetsTest::testEditPut
1..6
```

Same results with OAuth1a.

**Comment by MarkLL** [comment]
OK, Just updated my test environment to current staging, composer install for saml (plus lots of updates), run migrations, logged in and all good :)

Ran the same Asset test with basic Auth and Admin user and it worked...
```
C:\MarkLL\api-library>phpunit -v --debug --tap tests\Api\AssetsTest.php
TAP version 13
ok 1 - Mautic\Tests\Api\AssetsTest::testGetList
ok 2 - Mautic\Tests\Api\AssetsTest::testGetListOfSpecificIds
ok 3 - Mautic\Tests\Api\AssetsTest::testCreateWithLocalFileGetAndDelete
ok 4 - Mautic\Tests\Api\AssetsTest::testCreateWithRemoteFileGetAndDelete
ok 5 - Mautic\Tests\Api\AssetsTest::testEditPatch
ok 6 - Mautic\Tests\Api\AssetsTest::testEditPut
1..6
```
Switch to a non-admin user (set up to test minimum roles) and it fails with `You do not have access to the requested area/action`. I suspect if i use the same user for the OAuth authorization I'd get the same thing.

Is it just the AssetTest failing with BasicAuth?

**Comment by MarkLL** [comment]
OK, so ran all the testcases with BasicAuth configured with admin user:
```
C:\MarkLL\api-library>phpunit -v --debug --tap
TAP version 13
ok 1 - Mautic\Tests\Api\AssetsTest::testGetList
ok 2 - Mautic\Tests\Api\AssetsTest::testGetListOfSpecificIds
ok 3 - Mautic\Tests\Api\AssetsTest::testCreateWithLocalFileGetAndDelete
ok 4 - Mautic\Tests\Api\AssetsTest::testCreateWithRemoteFileGetAndDelete
ok 5 - Mautic\Tests\Api\AssetsTest::testEditPatch
ok 6 - Mautic\Tests\Api\AssetsTest::testEditPut
ok 7 - Mautic\Tests\Api\Auth\BasicAuthTest::testParameterExceptionErrorNoUserName
ok 8 - Mautic\Tests\Api\Auth\BasicAuthTest::testParameterExceptionErrorNoPassword
ok 9 - Mautic\Tests\Api\Auth\BasicAuthTest::testParameterExceptionErrorEmptyUserName
ok 10 - Mautic\Tests\Api\Auth\BasicAuthTest::testParameterExceptionErrorEmptyPassword
ok 11 - Mautic\Tests\Api\Auth\BasicAuthTest::testConfigReady
ok 12 - Mautic\Tests\Api\Auth\BasicAuthTest::testPublicInterface
ok 13 - Mautic\Tests\Api\Auth\BasicAuthTest::testGetList
ok 14 - Mautic\Tests\Api\CampaignsTest::testGetList
ok 15 - Mautic\Tests\Api\CampaignsTest::testGetListOfSpecificIds
ok 16 - Mautic\Tests\Api\CampaignsTest::testCreateGetAndDelete
ok 17 - Mautic\Tests\Api\CampaignsTest::testEditPatch
ok 18 - Mautic\Tests\Api\CampaignsTest::testEditPut
ok 19 - Mautic\Tests\Api\CampaignsTest::testEventAndSourceDeleteViaPut
ok 20 - Mautic\Tests\Api\CampaignsTest::testAddAndRemove
ok 21 - Mautic\Tests\Api\CategoriesTest::testGetList
ok 22 - Mautic\Tests\Api\CategoriesTest::testGetListOfSpecificIds
ok 23 - Mautic\Tests\Api\CategoriesTest::testCreateGetAndDelete
ok 24 - Mautic\Tests\Api\CategoriesTest::testEditPatch
ok 25 - Mautic\Tests\Api\CategoriesTest::testEditPut
ok 26 - Mautic\Tests\Api\CompaniesTest::testGetList
ok 27 - Mautic\Tests\Api\CompaniesTest::testCreateGetAndDelete
ok 28 - Mautic\Tests\Api\CompaniesTest::testEditPatch
ok 29 - Mautic\Tests\Api\CompaniesTest::testEditPut
ok 30 - Mautic\Tests\Api\CompaniesTest::testAddAndRemove
ok 31 - Mautic\Tests\Api\ContactFieldsTest::testGetList
ok 32 - Mautic\Tests\Api\ContactFieldsTest::testCreateGetAndDelete
ok 33 - Mautic\Tests\Api\ContactFieldsTest::testCreateGetAndDeleteOfLookupField
ok 34 - Mautic\Tests\Api\ContactFieldsTest::testBooleanField
ok 35 - Mautic\Tests\Api\ContactFieldsTest::testDefaultFieldValue
ok 36 - Mautic\Tests\Api\ContactFieldsTest::testEditPatch
ok 37 - Mautic\Tests\Api\ContactFieldsTest::testEditPut
ok 38 - Mautic\Tests\Api\CompanyFieldTest::testBooleanField
ok 39 - Mautic\Tests\Api\CompanyFieldTest::testDefaultFieldValue
ok 40 - Mautic\Tests\Api\CompanyFieldTest::testGetList
ok 41 - Mautic\Tests\Api\CompanyFieldTest::testCreateGetAndDelete
ok 42 - Mautic\Tests\Api\CompanyFieldTest::testCreateGetAndDeleteOfLookupField
ok 43 - Mautic\Tests\Api\CompanyFieldTest::testEditPatch
ok 44 - Mautic\Tests\Api\CompanyFieldTest::testEditPut
ok 45 - Mautic\Tests\Api\ContactFieldsTest::testGetList
ok 46 - Mautic\Tests\Api\ContactFieldsTest::testCreateGetAndDelete
ok 47 - Mautic\Tests\Api\ContactFieldsTest::testCreateGetAndDeleteOfLookupField
ok 48 - Mautic\Tests\Api\ContactFieldsTest::testBooleanField
ok 49 - Mautic\Tests\Api\ContactFieldsTest::testDefaultFieldValue
ok 50 - Mautic\Tests\Api\ContactFieldsTest::testEditPatch
ok 51 - Mautic\Tests\Api\ContactFieldsTest::testEditPut
ok 52 - Mautic\Tests\Api\ContactsTest::testGetList
ok 53 - Mautic\Tests\Api\ContactsTest::testGetListOfSpecificIds
ok 54 - Mautic\Tests\Api\ContactsTest::testGetListOfSpecificSegment
ok 55 - Mautic\Tests\Api\ContactsTest::testGetFieldList
ok 56 - Mautic\Tests\Api\ContactsTest::testGetSegmentsList
not ok 57 - Failure: Mautic\Tests\Api\ContactsTest::testGetEvents
  ---
  message: 'Failed asserting that two strings are equal.'
  severity: fail
  data:
      got: lead.create
      expected: lead.identified
  ...
ok 58 - Mautic\Tests\Api\ContactsTest::testGetEventsAdvanced
ok 59 - Mautic\Tests\Api\ContactsTest::testCreateGetAndDelete
ok 60 - Mautic\Tests\Api\ContactsTest::testDncAddInCreate
ok 61 - Mautic\Tests\Api\ContactsTest::testDncAddRemoveEndpoints
ok 62 - Mautic\Tests\Api\ContactsTest::testEditPatch
ok 63 - Mautic\Tests\Api\ContactsTest::testEditPatchFormError
ok 64 - Mautic\Tests\Api\ContactsTest::testEditPut
ok 65 - Mautic\Tests\Api\ContactsTest::testAddPoints
ok 66 - Mautic\Tests\Api\ContactsTest::testSubtractPoints
ok 67 - Mautic\Tests\Api\DataTest::testUnsupportedFeatures
ok 68 - Mautic\Tests\Api\DataTest::testGetListData
ok 69 - Mautic\Tests\Api\DataTest::testGetCoreWidgetsData
ok 70 - Mautic\Tests\Api\DataTest::testGetAssetWidgetsData
ok 71 - Mautic\Tests\Api\DataTest::testGetCampaignWidgetsData
ok 72 - Mautic\Tests\Api\DataTest::testGetEmailWidgetsData
ok 73 - Mautic\Tests\Api\DataTest::testGetFormWidgetsData
ok 74 - Mautic\Tests\Api\DataTest::testGetContactWidgetsData
ok 75 - Mautic\Tests\Api\DataTest::testGetPageWidgetsData
ok 76 - Mautic\Tests\Api\DataTest::testGetPointWidgetsData
ok 77 - Mautic\Tests\Api\DataTest::testGetStageWidgetsData
ok 78 - Mautic\Tests\Api\DevicesTest::testGetList
ok 79 - Mautic\Tests\Api\DevicesTest::testGetListOfSpecificIds
ok 80 - Mautic\Tests\Api\DevicesTest::testCreateGetAndDelete
ok 81 - Mautic\Tests\Api\DevicesTest::testEditPatch
ok 82 - Mautic\Tests\Api\DevicesTest::testEditPut
ok 83 - Mautic\Tests\Api\DynamicContentsTest::testGetList
ok 84 - Mautic\Tests\Api\DynamicContentsTest::testGetListOfSpecificIds
ok 85 - Mautic\Tests\Api\DynamicContentsTest::testCreateGetAndDelete
ok 86 - Mautic\Tests\Api\DynamicContentsTest::testEditPatch
ok 87 - Mautic\Tests\Api\DynamicContentsTest::testEditPut
ok 88 - Mautic\Tests\Api\EmailsTest::testGetList
ok 89 - Mautic\Tests\Api\EmailsTest::testGetListOfSpecificIds
ok 90 - Mautic\Tests\Api\EmailsTest::testCreateGetAndDelete
ok 91 - Mautic\Tests\Api\EmailsTest::testEditPatch
ok 92 - Mautic\Tests\Api\EmailsTest::testEditPut
ok 93 - Mautic\Tests\Api\EmailsTest::testSendToSegment
ok 94 - Mautic\Tests\Api\EmailsTest::testSendToContact
ok 95 - Mautic\Tests\Api\FilesTest::testGetList
ok 96 - Mautic\Tests\Api\FilesTest::testGetListSubdir
ok 97 - Mautic\Tests\Api\FilesTest::testGetListAssetFiles
ok 98 - Mautic\Tests\Api\FilesTest::testCreateAndDeleteImage
ok 99 - Mautic\Tests\Api\FilesTest::testCreateAndDeletePhpScript
ok 100 - Mautic\Tests\Api\FilesTest::testCreateAndDeleteImageInSubdir
ok 101 - Mautic\Tests\Api\FilesTest::testCreateAndDeleteAsset
ok 102 - Mautic\Tests\Api\FormsTest::testGetList
ok 103 - Mautic\Tests\Api\FormsTest::testGetListOfSpecificIds
ok 104 - Mautic\Tests\Api\FormsTest::testCreateGetAndDelete
ok 105 - Mautic\Tests\Api\FormsTest::testDeleteFields
ok 106 - Mautic\Tests\Api\FormsTest::testDeleteActions
ok 107 - Mautic\Tests\Api\FormsTest::testEditPatch
ok 108 - Mautic\Tests\Api\FormsTest::testEditPut
ok 109 - Mautic\Tests\Api\FormsTest::testFieldAndActionDeleteViaPut
ok 110 - Mautic\Tests\Api\LeadsTest::testGetList
ok 111 - Mautic\Tests\Api\LeadsTest::testGetListOfSpecificIds
ok 112 - Mautic\Tests\Api\LeadsTest::testGetListOfSpecificSegment
ok 113 - Mautic\Tests\Api\LeadsTest::testGetFieldList
ok 114 - Mautic\Tests\Api\LeadsTest::testGetSegmentsList
not ok 115 - Failure: Mautic\Tests\Api\LeadsTest::testGetEvents
  ---
  message: 'Failed asserting that two strings are equal.'
  severity: fail
  data:
      got: lead.create
      expected: lead.identified
  ...
ok 116 - Mautic\Tests\Api\LeadsTest::testGetEventsAdvanced
ok 117 - Mautic\Tests\Api\LeadsTest::testCreateGetAndDelete
ok 118 - Mautic\Tests\Api\LeadsTest::testDncAddInCreate
ok 119 - Mautic\Tests\Api\LeadsTest::testDncAddRemoveEndpoints
ok 120 - Mautic\Tests\Api\LeadsTest::testEditPatch
ok 121 - Mautic\Tests\Api\LeadsTest::testEditPatchFormError
ok 122 - Mautic\Tests\Api\LeadsTest::testEditPut
ok 123 - Mautic\Tests\Api\LeadsTest::testAddPoints
ok 124 - Mautic\Tests\Api\LeadsTest::testSubtractPoints
ok 125 - Mautic\Tests\Api\ListsTest::testGetList
ok 126 - Mautic\Tests\Api\ListsTest::testGetListOfSpecificIds
ok 127 - Mautic\Tests\Api\ListsTest::testGetListMinimal
ok 128 - Mautic\Tests\Api\ListsTest::testCreateGetAndDelete
ok 129 - Mautic\Tests\Api\ListsTest::testEditPatch
ok 130 - Mautic\Tests\Api\ListsTest::testEditPut
ok 131 - Mautic\Tests\Api\ListsTest::testAddAndRemove
ok 132 - Mautic\Tests\Api\NotesTest::testGetList
ok 133 - Mautic\Tests\Api\NotesTest::testGetListOfSpecificIds
ok 134 - Mautic\Tests\Api\NotesTest::testCreateGetAndDelete
ok 135 - Mautic\Tests\Api\NotesTest::testEditPatch
ok 136 - Mautic\Tests\Api\NotesTest::testEditPut
ok 137 - Mautic\Tests\Api\NotificationsTest::testGetList
not ok 138 - Failure: Mautic\Tests\Api\NotificationsTest::testGetListOfSpecificIds
  ---
  message: 'An exception occurred while executing ''INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'' with params [1, "2017-01-13 11:28:58", 1, "Admin User", null, null, null, null, null, null, "test", null, "en", null, "API test heading", "API test message", null, "template", null, null, 0, 0, null]:'
  severity: fail
  ...
not ok 139 - Failure: Mautic\Tests\Api\NotificationsTest::testCreateGetAndDelete
  ---
  message: 'An exception occurred while executing ''INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'' with params [1, "2017-01-13 11:29:00", 1, "Admin User", null, null, null, null, null, null, "test", null, "en", null, "API test heading", "API test message", null, "template", null, null, 0, 0, null]:'
  severity: fail
  ...
not ok 140 - Failure: Mautic\Tests\Api\NotificationsTest::testEditPatch
  ---
  message: 'An exception occurred while executing ''INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'' with params [1, "2017-01-13 11:29:02", 1, "Admin User", null, null, null, null, null, null, "test", null, "en", null, "API test heading", "API test message", null, "template", null, null, 0, 0, null]:'
  severity: fail
  ...
not ok 141 - Failure: Mautic\Tests\Api\NotificationsTest::testEditPut
  ---
  message: 'An exception occurred while executing ''INSERT INTO push_notifications (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, name, description, lang, url, heading, message, button, notification_type, publish_up, publish_down, read_count, sent_count, category_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'' with params [1, "2017-01-13 11:29:04", 1, "Admin User", null, null, null, null, null, null, "test", null, "en", null, "API test heading", "API test message", null, "template", null, null, 0, 0, null]:'
  severity: fail
  ...
ok 142 - Mautic\Tests\Api\PagesTest::testGetList
ok 143 - Mautic\Tests\Api\PagesTest::testGetListOfSpecificIds
ok 144 - Mautic\Tests\Api\PagesTest::testCreateGetAndDelete
ok 145 - Mautic\Tests\Api\PagesTest::testEditPatch
ok 146 - Mautic\Tests\Api\PagesTest::testEditPut
ok 147 - Mautic\Tests\Api\PointTriggersTest::testGetList
ok 148 - Mautic\Tests\Api\PointTriggersTest::testGetListOfSpecificIds
ok 149 - Mautic\Tests\Api\PointTriggersTest::testCreateGetAndDelete
ok 150 - Mautic\Tests\Api\PointTriggersTest::testEditPatch
ok 151 - Mautic\Tests\Api\PointTriggersTest::testEditPut
ok 152 - Mautic\Tests\Api\PointTriggersTest::testEventDeleteViaPut
ok 153 - Mautic\Tests\Api\PointTriggersTest::testDeleteEvents
ok 154 - Mautic\Tests\Api\PointTriggersTest::testGetEventTypes
ok 155 - Mautic\Tests\Api\PointsTest::testGetList
ok 156 - Mautic\Tests\Api\PointsTest::testGetListOfSpecificIds
ok 157 - Mautic\Tests\Api\PointsTest::testCreateGetAndDelete
ok 158 - Mautic\Tests\Api\PointsTest::testEditPatch
ok 159 - Mautic\Tests\Api\PointsTest::testEditPut
ok 160 - Mautic\Tests\Api\PointsTest::testGetPointActionTypes
ok 161 - Mautic\Tests\Api\ReportsTest::testGet
ok 162 - Mautic\Tests\Api\ReportsTest::testGetList
ok 163 - Mautic\Tests\Api\ResponseInfoTest::testGetVersion
ok 164 - Mautic\Tests\Api\ResponseInfoTest::testResponseInfo
ok 165 - Mautic\Tests\Api\ResponseInfoTest::testResponseHeaders
ok 166 - Mautic\Tests\Api\RolesTest::testGetList
ok 167 - Mautic\Tests\Api\RolesTest::testGetListOfSpecificIds
ok 168 - Mautic\Tests\Api\RolesTest::testCreateGetAndDelete
ok 169 - Mautic\Tests\Api\RolesTest::testEditPatch
ok 170 - Mautic\Tests\Api\RolesTest::testEditPut
ok 171 - Mautic\Tests\Api\SegmentsTest::testGetList
ok 172 - Mautic\Tests\Api\SegmentsTest::testGetListOfSpecificIds
ok 173 - Mautic\Tests\Api\SegmentsTest::testGetListMinimal
ok 174 - Mautic\Tests\Api\SegmentsTest::testCreateGetAndDelete
ok 175 - Mautic\Tests\Api\SegmentsTest::testEditPatch
ok 176 - Mautic\Tests\Api\SegmentsTest::testEditPut
ok 177 - Mautic\Tests\Api\SegmentsTest::testAddAndRemove
ok 178 - Mautic\Tests\Api\SmsesTest::testGetList
ok 179 - Mautic\Tests\Api\SmsesTest::testGetListOfSpecificIds
ok 180 - Mautic\Tests\Api\SmsesTest::testCreateGetAndDelete
ok 181 - Mautic\Tests\Api\SmsesTest::testEditPatch
ok 182 - Mautic\Tests\Api\SmsesTest::testEditPut
ok 183 - Mautic\Tests\Api\StagesTest::testGetList
ok 184 - Mautic\Tests\Api\StagesTest::testGetListOfSpecificIds
ok 185 - Mautic\Tests\Api\StagesTest::testCreateGetAndDelete
ok 186 - Mautic\Tests\Api\StagesTest::testEditPatch
ok 187 - Mautic\Tests\Api\StagesTest::testEditPut
ok 188 - Mautic\Tests\Api\StagesTest::testAddAndRemove
ok 189 - Mautic\Tests\Api\StatsTest::testGetTables
ok 190 - Mautic\Tests\Api\StatsTest::testGetSimple
ok 191 - Mautic\Tests\Api\StatsTest::testGetStartLimit
ok 192 - Mautic\Tests\Api\StatsTest::testGetOrderSimple
ok 193 - Mautic\Tests\Api\StatsTest::testGetOrderAsc
ok 194 - Mautic\Tests\Api\StatsTest::testGetOrderDesc
ok 195 - Mautic\Tests\Api\StatsTest::testGetWhereEqual
ok 196 - Mautic\Tests\Api\StatsTest::testGetWhereGreaterThan
ok 197 - Mautic\Tests\Api\UsersTest::testGetList
ok 198 - Mautic\Tests\Api\UsersTest::testGetListOfSpecificIds
ok 199 - Mautic\Tests\Api\UsersTest::testCreateGetAndDelete
ok 200 - Mautic\Tests\Api\UsersTest::testEditPatch
ok 201 - Mautic\Tests\Api\UsersTest::testEditPut
ok 202 - Mautic\Tests\Api\UsersTest::testGetSelf
ok 203 - Mautic\Tests\Api\UsersTest::testGetSelfPermissionsString
ok 204 - Mautic\Tests\Api\UsersTest::testGetSelfPermissionsArray
1..204
```

the `testGetEvents` tests have always failed. will look at them. Not familiar with the notifications tests; otherwise, looks ok to me.

**Comment by MarkLL** [comment]
so the reason for the testGetEvents failures is because the events are not in the expected order. for whatever reason, the array returns in the expected order only by specifying a descening order
```
Expected order: Array(
    [0] => lead.create
    [1] => lead.identified
)

Events Array(
    [events] => Array(
            [0] => Array(
                    [event] => lead.identified
                    [icon] => fa-user
                    [eventType] => Contact identified
                    [eventPriority] => -4
                    [timestamp] => 2017-01-13T12:08:44+00:00
                    [featured] => 1
                )
            [1] => Array(
                    [event] => lead.create
                    [icon] => fa-user-secret
                    [eventType] => Contact created
                    [eventPriority] => -5
                    [timestamp] => 2017-01-13T12:08:44+00:00
                )
        )

    [filters] => Array(
            [search] =>
            [includeEvents] => Array()
            [excludeEvents] => Array()
        )
    [order] => Array(
            [0] =>
            [1] => ASC
        )
...
)
```

**Comment by kerleba** [comment]
Works for me :+1: 
@MarkLL thank you for this PR
@escopecz Is anything needed before merge?

**Comment by jozephbrasil** [comment]
Tested... Working for me too.

**Comment by escopecz** [comment]
I don't know what I'm doing wrong, but if I try to test with `'AuthMethod' => 'BasicAuth',` and `userName`, `password` filled to my admin user credentials, I get this:
```
phpunit --stop-on-failure
PHPUnit 5.7.5 by Sebastian Bergmann and contributors.

F

Time: 693 ms, Memory: 12.00MB

There was 1 failure:

1) Mautic\Tests\Api\AssetsTest::testGetList
access_denied: OAuth2 authentication required
Failed asserting that true is false.

tests/Api/MauticApiTestCase.php:44
tests/Api/MauticApiTestCase.php:94
tests/Api/AssetsTest.php:27
```

Can anyone tell me what I'm doing wrong? It seems that I'm the only one who cannot get the unit tests to pass.

Is there a reason why the `AuthMethod` is required in the config for the tests? Isn't it a backward compatibility break? If I test without it, I get 
```
1) Mautic\Tests\Api\Auth\BasicAuthTest::testConfigReady
AuthMethod Check failed. Check AuthMethod in local.config.php.
Failed asserting that false is true.

/Users/jan/dev/mautic-api/tests/Api/Auth/BasicAuthTest.php:95
```

**Comment by MarkLL** [comment]
@escopecz you don't have the latest version of the code I suspect. See if https://gist.github.com/MarkLL/71db98b6522487286226bfea5ad0dcc0 helps.

**Comment by MarkLL** [comment]
@escopecz I had removed `baseUrl` from my original `BasicAuth` implementation as I did not need it - to simplify. It actually was never documented in the dist file but it is now :)

**Comment by isleshocky77** [comment]
When on this branch and trying to enable Basic Auth I'm receiving a validation error that SAML Authentication information needs to be completed. Is this correct? What does SAML have to do with Basic Auth?

**Comment by isleshocky77** [comment]
I tested this branch locally and the tests pass as well as I'm able to use the API with BasicAuth with this PR and mautic 2.5.2-dev

**Comment by jozephbrasil** [comment]
When this PR will be merged to master?

**Comment by isleshocky77** [comment]
@MarkLL @escopecz We have an update to have BasicAuth support updating curl's timeout (CURLOPT_TIMEOUT). How would you like me to submit it?

**Comment by MarkLL** [comment]
@isleshocky77 Maybe we wait until it's merged! Any changes now might lead to further delays!!!

Also, surely this should apply to the normal OAuth class as well? or is there something about basicAuth that requires the change?

**Comment by isleshocky77** [comment]
@MarkLL I'm fine with waiting. The patch would apply to the `OAuth` class as well; however, maybe there would/should be a way of refactoring to have the `makeRequest` curl code put somewhere else, otherwise it would just be duplicated.

**Comment by escopecz** [comment]
This PR works good for me. 👍  If you test with 2.6.0, make sure you applied https://github.com/mautic/mautic/pull/3413 to avoid some Mautic bugs.

**Comment by isleshocky77** [comment]
@MarkLL New PR put in over here (#92). In the meantime, @alanhartless already did the refactor of an `AbsractAuth` so I've put the code in there. Looks like this PR should now be all closed out.

**Pull request merged**
